os: linux
sudo: required
language: minimal
install: skip
services: docker
script:
  - export REPOSITORY_URL=$(git remote -v | awk '{print $2}')
  - env > .env
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then docker-compose down && docker-compose up --abort-on-container-exit travis-build; fi'
  - 'if [ "$TRAVIS_BRANCH" != "master" ]; then docker-compose down && docker-compose up --abort-on-container-exit travis-pull-request-build; fi'
