version: '3'
services:
  travis-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    command: ./builder.sh deploy
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
    env_file: .env

  travis-pull-request-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    command: ./gradlew build -i
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
